name: Rust CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy, rustfmt

    - name: Rust Cache
      uses: Swatinem/rust-cache@v2

    - name: Check Formatting
      run: cargo fmt --all -- --check

    - name: Run Clippy
      run: cargo clippy --workspace -- -D warnings

    - name: Run Tests
      run: cargo test --workspace -- --nocapture
      env:
        RUST_BACKTRACE: 1
        HTTP_URL: ${{ secrets.HTTP_URL }}
        RPC_URL: ${{ secrets.RPC_URL }}
        WSS_URL: ${{ secrets.WSS_URL }}
